using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Permissions;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: AllowPartiallyTrustedCallersAttribute()]
[assembly: SecurityPermissionAttribute(SecurityAction.RequestMinimum)]
[assembly: AssemblyCompanyAttribute("http://www.springframework.net")]
[assembly: AssemblyCopyrightAttribute("Copyright 2010-2011 Spring.NET Framework Team.")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.0.4111")]
[assembly: AssemblyFileVersionAttribute("1.0.0.4111")]
[assembly: AssemblyConfigurationAttribute("net-4.0.win32; release")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.4111; net-4.0.win32; release")]
[assembly: AssemblyDelaySignAttribute(false)]

